name: dove
favicon: null
layout_spectrum: 0.1780972897540778
typography_spectrum: 0.2589725849684328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#119ffd'
    - '#aaaaaa'
    - '#555555'
  brandStrength: 1
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
