name: dove
favicon: null
layout_spectrum: 0.1780972897540778
typography_spectrum: 0.2589725849684328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2480888250283897
  lightness: 0.19040771946310997
  saturation: 0.23320395546033978
  rhythmicContrast: 0.31802605744451284
purpose: []
